// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rycgbxuyqypsffuhljpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5Y2dieHV5cXlwc2ZmdWhsanB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjAwNjAsImV4cCI6MjA2NzQ5NjA2MH0.JM9CaqS7J0xn57IwxfUgjfHlcQ2CCY1sCM4ZBW2bJ00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});